---
- hosts: web
  name: This is a play within a playbook
  become: yes
  gather_facts: no

  vars:
    httpd_packages:
      - httpd
      - mod_wsgi
    apache_test_message: This test message was updated by a job template at {{ ansible_date_time.date }} {{ ansible_date_time.time }}
    apache_max_keep_alive_requests: 115

  tasks:
  - name: stop httpd
    service:
      name: httpd
      state: stopped

  #- name: create site-enabled directory
    #file:
      #name: /etc/httpd/conf/sites-enabled
      #state: directory
  
  - name: remove httpd.conf
    file:
      name: /etc/httpd/conf/httpd.conf
      state: absent
  
  - name: delete index.html
    file:
      name: /var/www/html/index.html
      state: absent
  
  - name: remove httpd packages
    yum:
      #name: "{{ item }}"
      name: "{{ httpd_packages }}"
      state: absent
    #with_items: "{{ httpd_packages }}"
    #loop: "{{ httpd_packages|flatten(levels=1) }}"
    #notify: restart apache service

  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted
        enabled: yes
