---
- hosts: localhost
  name: CONFIGURE ANSIBLE TOWER FOR BEN BLASCO
  #become: yes
  gather_facts: no

  tasks:
  - name: CREATE THE CREDENTIAL FOR WEB SERVERS
    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_credential_module.html
    tower_credential:
      name: Web server credential
      description: Credentials for web servers
      organization: Default
      username: student1
      password: ansible
      # kind: ssh is equivalent to Tower "Machine" credential
      kind: ssh
      become_method: sudo

      tower_host: https://13.229.90.84
      tower_username: admin
      tower_password: ansible
      #tower_config_file: "tower_cli.cfg"
      tower_verify_ssl: false
      state: present

  - name: CREATE THE PROJECT FOR WEB SERVERS
    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_project_module.html
    tower_project:
      name: Web server deployment project
      description: Collection of playbooks for deploying and configuring web servers
      organization: Default

      scm_type: git
      #scm_url: https://github.com/eraser215/ansibledemo.git 
      scm_url: https://github.com/eraser215/ansibledemo
      scm_clean: yes
      scm_delete_on_update: yes
      scm_update_on_launch: yes

      tower_host: https://13.229.90.84
      tower_username: admin
      tower_password: ansible
      #tower_config_file: "tower_cli.cfg"
      tower_verify_ssl: false
      state: present
