---
- hosts: localhost
  name: CONFIGURE ANSIBLE TOWER FOR BEN BLASCO
  #become: yes
  gather_facts: no

  tasks:
  - name: CREATE THE CREDENTIAL FOR WEB SERVERS
    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_credential_module.html
    tower_credential:
      name: Web server credential
      description: Credentials for web servers
      organization: Default
      username: student1
      password: ansible
      # kind: ssh is equivalent to Tower "Machine" credential
      kind: ssh
      become_method: sudo

      tower_host: https://13.229.87.223
      tower_username: admin
      tower_password: ansible
      #tower_config_file: "tower_cli.cfg"
      tower_verify_ssl: false
      state: present

  - name: CREATE THE PROJECT FOR WEB SERVERS
    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_project_module.html
    tower_project:
      name: Web server deployment project
      description: Collection of playbooks for deploying and configuring web servers
      organization: Default

      scm_type: git
      #scm_url: https://github.com/eraser215/ansibledemo.git 
      scm_url: https://github.com/eraser215/ansibledemo
      scm_clean: yes
      scm_delete_on_update: yes
      scm_update_on_launch: yes

      tower_host: https://13.229.87.223
      tower_username: admin
      tower_password: ansible
      #tower_config_file: "tower_cli.cfg"
      tower_verify_ssl: false
      state: present

  - name: CREATE THE TOWER INVENTORY FOR WEB SERVERS
    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_inventory_module.html
    tower_inventory:
      name: Web server inventory
      description: Inventory of web servers
      organization: Default

      tower_host: https://13.229.87.223
      tower_username: admin
      tower_password: ansible
      #tower_config_file: "tower_cli.cfg"
      tower_verify_ssl: false
      state: present

#  - name: IMPORT THE TOWER INVENTORY FOR WEB SERVERS
#    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_inventory_source_module.html
#    tower_inventory_source:
#      name: Web server inventory source
#      description: Inventory source for web servers
#      #organization: Default
#      inventory: Web server inventory
#      source: file
#      #source_path: "/home/student1/ansibledemo/apache_basic/hosts"
#      source_path: "/tmp/hosts"



#      tower_host: https://13.229.87.223
#      tower_username: admin
#      tower_password: ansible
#      #tower_config_file: "tower_cli.cfg"
#      tower_verify_ssl: false
#      state: present

  - name: (KLUDGE) IMPORT THE TOWER INVENTORY FOR WEB SERVERS
    become: yes
    #sudo tower-manage inventory_import --source=/home/student1/ansibledemo/apache_basic/hosts --inventory-name="Web server inventory"
    shell: /usr/bin/tower-manage inventory_import --source=/home/student1/ansibledemo/apache_basic/hosts --inventory-name="Web server inventory"
    register: shell_output

  - name: (KLUDGE) SHOW THE TOWER INVENTORY IMPORT RESULT
    debug:
      var: shell_output

  - name: CREATE THE TOWER JOB TEMPLATE FOR DEPLOYING WEB SERVERS
    # Documentation here: https://docs.ansible.com/ansible/latest/modules/tower_job_template_module.html
    tower_job_template:
      name: Web server deployment template
      description: Job template for running web server deployment playbook
      job_type: run
      inventory: Web server inventory
      project: Web server deployment project
      playbook: apache_basic/site_roles.yml
      credential: Web server credential
      limit: web
      become_enabled: yes
      #survey_enabled: yes


      tower_host: https://13.229.87.223
      tower_username: admin
      tower_password: ansible
      #tower_config_file: "tower_cli.cfg"
      tower_verify_ssl: false
      state: present
