---
- hosts: web
  name: This is a play within a playbook
  become: yes

  vars:
    httpd_packages:
      - httpd
      - mod_wsgi
    apache_test_message: This test message was updated by a job template at {{ ansible_date_time.date }} {{ ansible_date_time.time }}
    apache_max_keep_alive_requests: 115

  tasks:
  - name: install httpd packages
    yum:
      #name: "{{ item }}"
      name: "{{ httpd_packages }}"
      state: present
    #with_items: "{{ httpd_packages }}"
    #loop: "{{ httpd_packages|flatten(levels=1) }}"
    #notify: restart apache service


  - name: create site-enabled directory
    file:
      name: /etc/httpd/conf/sites-enabled
      state: directory
  
  - name: copy httpd.conf
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: restart apache service
  
  - name: copy index.html
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html
  
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: yes


  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted
        enabled: yes
